version: 2.1
executors:
  default:
    working_directory: ~/work
    docker:
      - image: cimg/python:3.10.4

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run: pyenv --version
      - run: pyenv install 3.9.12
      - run: python -m venv testenv
      - run: source testenv/bin/activate 
      - run: python -V
      - run: pip install -r requirements.txt
      - run: deactivate
      - save_cache:
          key: my-cache
          paths:
            - ~/work
  test:
    executor:
      name: default
    steps:
      - restore_cache:
          key: my-cache
      - run: ls
      - run: pwd
      - run: pyenv install 3.9.12
      - run: source testenv/bin/activate
      - run: python example1.py 
      - run: echo "done."
workflows:
  stl-maker:
    jobs:
      - build
      - test:
          requires:
            - build
